theme: jekyll-theme-slate
title: Welcome to thepydude's webpage! ![Image](https://drive.google.com/file/d/1yJ9ZSRjl-5DdHtjYp9Lr7tJMlIKE6329/view?usp=sharing)
description: Your friendly neighborhood Data Scientist
